---
version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get -y install make python3 python3-pip
      - pip install pelican
  build:
    commands:
      - make publish
artifacts:
  files:
    - '**/*'
  base-directory: output
  discard-paths: no
